import type { NextPage } from 'next'
import Head from 'next/head'
import Content from '../components/Content'
import HomePage from '../components/HomePage'
import Logo from '../components/Logo'
import Nav from '../components/Nav'
import Social from '../components/Social'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vigrious</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container'>
        <div className='header'>
          <Logo />
          <Nav />
        </div>
        <Content>
          <HomePage />
        </Content>
        <Social />
      </main>
    </div>
  )
}

export default Home
